import { AlertTriangle, FileInput, Plus, RotateCcw, Search } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import optionsDocument from "../../catalog/options.json";
import presetsDocument from "../../catalog/presets.json";
import { commandErrorMessage, type IniPreview, type ManagedChange } from "../api/commands";
import { Accordion } from "../components/Accordion";
import { Button } from "../components/Button";
import { DiffView } from "../components/DiffView";
import { Tooltip } from "../components/Tooltip";
import { Field, Notice, PageHeader } from "../components/shared";
import { useAppState } from "../state/AppState";

type CustomRow = { section: string; key: string; value: string };

export function EnginePage() {
  const { commands, language, text, setEngineDraft, setWriteInProgress } = useAppState();
  const [presetId, setPresetId] = useState("balanced");
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [managed, setManaged] = useState<Record<string, string | null>>(() => {
    const preset = presetsDocument.presets.find((item) => item.id === "balanced");
    return Object.fromEntries((preset?.changes ?? []).map((change) => [`${change.section}/${change.key}`, change.value] as const));
  });
  const [custom, setCustom] = useState<CustomRow[]>([]);
  const [customDraft, setCustomDraft] = useState<CustomRow>({ section: "", key: "", value: "" });
  const [paste, setPaste] = useState("");
  const [preview, setPreview] = useState<IniPreview | null>(null);
  const [replacementPreview, setReplacementPreview] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [result, setResult] = useState<string | null>(null);
  const [profileId, setProfileId] = useState("");
  const [profileName, setProfileName] = useState("");
  const [busy, setBusy] = useState(false);
  const inputGeneration = useRef(0);
  const previewRequest = useRef(0);
  const invalidate = () => { inputGeneration.current += 1; previewRequest.current += 1; setPreview(null); setReplacementPreview(false); setConfirmed(false); setResult(null); setBusy(false); };
  const visible = useMemo(() => optionsDocument.options.filter((option) => (status === "all" || option.status === status) && `${option.key} ${option.section} ${option.description.en} ${option.description.ko}`.toLowerCase().includes(search.toLowerCase())), [search, status]);
  const managedChanges: ManagedChange[] = Object.entries(managed).map(([compound, value]) => { const split = compound.indexOf("/"); return { section: compound.slice(0, split), key: compound.slice(split + 1), value }; });
  const changes: ManagedChange[] = [...managedChanges, ...custom.map((entry) => ({ ...entry }))];
  useEffect(() => { setEngineDraft(managedChanges, custom.map((row) => ({ ...row, provenance: "custom", runtime_verified: false }))); }, [managed, custom]);
  const requestPreview = async (load: () => Promise<IniPreview | null>, replacesWholeFile = false) => { const request = ++previewRequest.current; const generation = inputGeneration.current; setPreview(null); setReplacementPreview(false); setConfirmed(false); setResult(null); setBusy(true); try { const value = await load(); if (request === previewRequest.current && generation === inputGeneration.current && value) { setPreview(value); setReplacementPreview(replacesWholeFile); } } catch (error) { if (request === previewRequest.current) setResult(commandErrorMessage(error, language)); } finally { if (request === previewRequest.current) setBusy(false); } };
  const makeManagedPreview = () => requestPreview(() => commands.previewIni({ kind: "managed", changes }));
  const makePastePreview = () => requestPreview(() => commands.previewIni({ kind: "paste", text: paste }), true);
  const apply = async () => { if (!preview) return; setBusy(true); setWriteInProgress(true); try { const value = await commands.applyIni(preview.token, confirmed); setResult(text(`Applied and created backup ${value.backup_id}.`, `적용하고 백업 ${value.backup_id}을(를) 만들었습니다.`)); setPreview(null); setReplacementPreview(false); setConfirmed(false); } catch (error) { setResult(commandErrorMessage(error, language)); setPreview(null); setReplacementPreview(false); } finally { setBusy(false); setWriteInProgress(false); } };
  const selectPreset = (id: string) => { setPresetId(id); const preset = presetsDocument.presets.find((item) => item.id === id); setManaged(Object.fromEntries((preset?.changes ?? []).map((c) => [`${c.section}/${c.key}`, c.value] as const))); invalidate(); };
  const selectedPreset = presetsDocument.presets.find((preset) => preset.id === presetId)!;
  const optionStatusLabel = (value: string) => text(value.replace(/_/g, " "), ({ verified: "검증됨", community_reported: "커뮤니티 보고", experimental: "실험적", ignored: "무시됨", regressed: "회귀" } as Record<string, string>)[value] ?? value);
  const riskTooltip = (risk: string, verified: boolean) => text(`${risk.toUpperCase()} risk · ${verified ? "Runtime verified" : "Not runtime-verified"}`, `${({ low: "낮음", medium: "중간", high: "높음" } as Record<string, string>)[risk] ?? risk} 위험 · ${verified ? "런타임 검증됨" : "런타임 미검증"}`);
  const saveAsProfile = async () => { try { await commands.saveProfile({ schema_version: 1, id: profileId, name: profileName, revision: 0, patch: { schema_version: 1, managed_ini: managedChanges, custom_ini_entries: custom.map((row) => ({ ...row, provenance: "custom", runtime_verified: false })), process: { cpu_selection: { mode: "all" }, priority: "normal" } } }); setResult(text(`Saved profile ${profileName}.`, `${profileName} 프로필을 저장했습니다.`)); setProfileId(""); setProfileName(""); } catch (error) { setResult(commandErrorMessage(error, language)); } };
  return <div className="page"><PageHeader title="Engine.ini" description={text("Choose documented options, add custom keys, or paste/import a complete Engine.ini. Nothing is written before diff confirmation.", "문서화된 옵션, 사용자 키, 전체 Engine.ini 붙여넣기/가져오기를 지원합니다. diff 확인 전에는 파일을 쓰지 않습니다.")} actions={<Button onClick={() => void requestPreview(() => commands.previewIniImport(), true)}><FileInput aria-hidden="true" size={17} />{text("Import Engine.ini", "Engine.ini 가져오기")}</Button>} />
    <Notice kind="warning">{text("File presence is not proof of runtime effect. Options marked experimental, ignored, or regressed may do nothing or reduce stability.", "파일에 있어도 런타임 적용을 의미하지 않습니다. 실험적·무시됨·회귀 옵션은 효과가 없거나 안정성을 낮출 수 있습니다.")}</Notice>
    <Notice kind="warning">{text("Whole-file import or paste replaces Engine.ini and can remove unrelated or game-generated lines that are absent from the incoming file.", "전체 파일 가져오기 또는 붙여넣기는 Engine.ini를 교체하며 가져온 파일에 없는 관련 없는 줄이나 게임 생성 줄을 제거할 수 있습니다.")}</Notice>
    {result ? <Notice kind={result.startsWith("Applied") ? "success" : "warning"}>{result}</Notice> : null}
    <section className="toolbar"><Field label={text("Preset", "프리셋")}><select value={presetId} onChange={(event) => selectPreset(event.target.value)}>{presetsDocument.presets.map((preset) => <option key={preset.id} value={preset.id}>{preset.name[language]}</option>)}</select></Field><Field label={text("Search options", "옵션 검색")}><div className="input-icon"><Search aria-hidden="true" size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} /></div></Field><Field label={text("Evidence status", "근거 상태")}><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">{text("All statuses", "모든 상태")}</option><option value="verified">{text("Verified", "검증됨")}</option><option value="community_reported">{text("Community reported", "커뮤니티 보고")}</option><option value="experimental">{text("Experimental", "실험적")}</option><option value="ignored">{text("Ignored", "무시됨")}</option><option value="regressed">{text("Regressed", "회귀")}</option></select></Field></section>
    <p className="muted">{selectedPreset.description[language]}</p>
    <section className="option-list" aria-label="Engine.ini option catalog">{visible.map((option) => { const compound = `${option.section}/${option.key}`; const enabled = Object.prototype.hasOwnProperty.call(managed, compound); const deleting = enabled && managed[compound] === null; return <article className="option-row" key={compound}><div className="option-copy"><div className="option-key"><code>{option.key}</code><span className={`tag tag--${option.status}`}>{optionStatusLabel(option.status)}</span><Tooltip label={riskTooltip(option.risk, option.evidence.runtime_verified)}><button className="icon-button" aria-label={`Warning for ${option.key}`}><AlertTriangle aria-hidden="true" size={17} /></button></Tooltip></div><p>{option.description[language]}</p><small>[{option.section}] · {option.value_type}</small></div><div className="option-control"><label><input checked={enabled} onChange={(event) => { setManaged((current) => { const next = { ...current }; if (event.target.checked) next[compound] = option.constraints.allowed_values[0] ?? ""; else delete next[compound]; return next; }); invalidate(); }} type="checkbox" />{text("Manage", "관리")}</label><select aria-label={`Action for ${option.key}`} disabled={!enabled} value={deleting ? "remove" : "set"} onChange={(event) => { setManaged((current) => ({ ...current, [compound]: event.target.value === "remove" ? null : "" })); invalidate(); }}><option value="set">{text("Set value", "값 설정")}</option><option value="remove">{text("Remove key", "키 제거")}</option></select><input aria-label={`Value for ${option.key}`} disabled={!enabled || deleting} placeholder={option.constraints.allowed_values.join(" / ") || text("Empty value allowed", "빈 값 허용")} value={typeof managed[compound] === "string" ? managed[compound]! : ""} onChange={(event) => { setManaged((value) => ({ ...value, [compound]: event.target.value })); invalidate(); }} /></div></article>; })}</section>
    <Accordion title={text("Custom option (not in catalog)", "사용자 옵션 (카탈로그 외)")}><div className="custom-editor"><Notice kind="warning">{text("Custom options are preserved in shared profiles but are not runtime-verified by this app.", "사용자 옵션은 공유 프로필에 보존되지만 이 앱에서 런타임 검증되지 않았습니다.")}</Notice><div className="form-grid"><Field label={text("Section", "섹션")}><input value={customDraft.section} onChange={(e) => setCustomDraft({ ...customDraft, section: e.target.value })} /></Field><Field label={text("Key", "키")}><input value={customDraft.key} onChange={(e) => setCustomDraft({ ...customDraft, key: e.target.value })} /></Field><Field label={text("Value", "값")}><input value={customDraft.value} onChange={(e) => setCustomDraft({ ...customDraft, value: e.target.value })} /></Field><Button onClick={() => { if (customDraft.section && customDraft.key) { setCustom((rows) => [...rows, customDraft]); setCustomDraft({ section: "", key: "", value: "" }); invalidate(); } }}><Plus aria-hidden="true" size={17} />{text("Add option", "옵션 추가")}</Button></div>{custom.map((row, index) => <div className="custom-row" key={`${row.section}-${row.key}-${index}`}><span>[{row.section}]</span><code>{row.key}={row.value}</code><Button onClick={() => { setCustom((items) => items.filter((_, itemIndex) => itemIndex !== index)); invalidate(); }}>{text("Remove", "제거")}</Button></div>)}<Button disabled={!changes.length || busy} onClick={() => void makeManagedPreview()}>{text("Preview managed changes", "관리 변경 미리보기")}</Button></div></Accordion>
    <Accordion title={text("Save these options as a profile", "이 옵션을 프로필로 저장")}><div className="form-grid"><Field label={text("Profile id", "프로필 ID")}><input value={profileId} onChange={(event) => setProfileId(event.target.value)} /></Field><Field label={text("Display name", "표시 이름")}><input value={profileName} onChange={(event) => setProfileName(event.target.value)} /></Field><Button disabled={!profileId || !profileName || !changes.length} onClick={() => void saveAsProfile()}>{text("Save profile", "프로필 저장")}</Button></div></Accordion>
    <Accordion title={text("Paste a complete Engine.ini", "전체 Engine.ini 붙여넣기")}><div className="raw-editor"><Notice kind="warning">{text("This replaces the complete Engine.ini. Unrelated or game-generated lines missing from the pasted file may be removed.", "전체 Engine.ini를 교체합니다. 붙여넣은 파일에 없는 관련 없는 줄이나 게임 생성 줄은 제거될 수 있습니다.")}</Notice><Field label={text("Engine.ini content", "Engine.ini 내용")} hint={text("Maximum size and encoding are validated by the native app.", "최대 크기와 인코딩은 네이티브 앱에서 검증합니다.")}><textarea rows={12} spellCheck={false} value={paste} onChange={(event) => { setPaste(event.target.value); invalidate(); }} /></Field><Button disabled={!paste.trim() || busy} onClick={() => void makePastePreview()}>{text("Preview pasted file", "붙여넣은 파일 미리보기")}</Button></div></Accordion>
    {preview ? <div className="apply-panel">{replacementPreview ? <Notice kind="warning">{text("Full-file replacement: review removed lines carefully. Unrelated and game-generated settings can be deleted by this exact preview.", "전체 파일 교체: 제거되는 줄을 주의 깊게 확인하세요. 이 미리보기로 관련 없는 설정과 게임 생성 설정이 삭제될 수 있습니다.")}</Notice> : null}<DiffView preview={preview} /><label className="check-row"><input checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} type="checkbox" />{replacementPreview ? text("Confirm backup and destructive full-file replacement for this exact preview", "백업 및 이 미리보기의 전체 파일 교체를 확인합니다") : text("Confirm backup creation and apply this exact preview", "백업 생성 후 이 미리보기 적용을 확인합니다")}</label><div className="action-row"><Button onClick={() => { setPreview(null); setReplacementPreview(false); setConfirmed(false); }}><RotateCcw aria-hidden="true" size={17} />{text("Discard preview", "미리보기 취소")}</Button><Button disabled={!confirmed || busy} variant="primary" onClick={() => void apply()}>{text("Back up and apply", "백업 후 적용")}</Button></div></div> : null}
  </div>;
}
