import { Download, Eye, Save, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { commandErrorMessage, type CustomProfile, type IniPreview, type ProfileImportCandidate } from "../api/commands";
import { Button } from "../components/Button";
import { DiffView } from "../components/DiffView";
import { EmptyState, Field, Notice, PageHeader } from "../components/shared";
import { useAppState } from "../state/AppState";

export function ProfilesPage() {
  const { commands, profiles, refresh, snapshot, text, profileDraft, language } = useAppState();
  const [candidate, setCandidate] = useState<ProfileImportCandidate | null>(null);
  const [selected, setSelected] = useState<CustomProfile | null>(null);
  const [iniPreview, setIniPreview] = useState<IniPreview | null>(null);
  const [confirmIni, setConfirmIni] = useState(false);
  const [id, setId] = useState("");
  const [name, setName] = useState("");
  const [draftId, setDraftId] = useState("");
  const [draftName, setDraftName] = useState("");
  const [editId, setEditId] = useState("");
  const [editName, setEditName] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const importRequest = useRef(0);
  const profilePreviewRequest = useRef(0);
  const importProfile = async () => { const request = ++importRequest.current; setCandidate(null); setId(""); setName(""); try { const value = await commands.importProfile(); if (request !== importRequest.current) return; setCandidate(value); if (value) { setId(value.preview.display_name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); setName(value.preview.display_name); } } catch (error) { if (request === importRequest.current) { setMessage(commandErrorMessage(error, language)); setCandidate(null); } } };
  const saveImport = async () => { if (!candidate) return; try { const profile = await commands.saveImportedProfile(candidate.token, id, name); setMessage(text(`Saved ${profile.name}.`, `${profile.name} 프로필을 저장했습니다.`)); setCandidate(null); await refresh(); } catch { setMessage(text("The import token was consumed or expired. Import the file again, then choose a new id.", "가져오기 토큰이 사용되었거나 만료되었습니다. 파일을 다시 가져온 뒤 새 ID를 선택하세요.")); setCandidate(null); } };
  const saveCurrent = async () => { const profile: CustomProfile = { schema_version: 1, id: draftId, name: draftName, revision: 0, patch: profileDraft }; try { await commands.saveProfile(profile); setMessage(text(`Saved ${draftName}.`, `${draftName} 프로필을 저장했습니다.`)); setDraftId(""); setDraftName(""); await refresh(); } catch (error) { setMessage(commandErrorMessage(error, language)); } };
  const previewSelected = async (profile: CustomProfile) => { const request = ++profilePreviewRequest.current; setSelected(profile); setEditId(`${profile.id}-copy`); setEditName(`${profile.name} Copy`); setConfirmIni(false); setIniPreview(null); try { const value = await commands.previewIni({ kind: "managed", changes: [...profile.patch.managed_ini, ...profile.patch.custom_ini_entries.map(({ section, key, value }) => ({ section, key, value }))] }); if (request === profilePreviewRequest.current) setIniPreview(value); } catch (error) { if (request === profilePreviewRequest.current) setMessage(commandErrorMessage(error, language)); } };
  const warningLabel = (warning: string) => text(warning.replace(/_/g, " "), ({ device_specific_cpu_reset: "장치별 CPU 선택이 초기화됨", elevated_priority: "높은 우선도 포함" } as Record<string, string>)[warning] ?? warning.replace(/_/g, " "));
  const priorityLabel = (priority: string) => text(priority.replace(/_/g, " "), ({ idle: "유휴", below_normal: "낮음", normal: "보통", above_normal: "높음", high: "매우 높음", realtime: "실시간" } as Record<string, string>)[priority] ?? priority.replace(/_/g, " "));
  const applyIni = async () => { if (!iniPreview) return; try { await commands.applyIni(iniPreview.token, confirmIni); setMessage(text("Profile Engine.ini changes were backed up and applied.", "프로필의 Engine.ini 변경을 백업 후 적용했습니다.")); } catch (error) { setMessage(commandErrorMessage(error, language)); } finally { setIniPreview(null); setConfirmIni(false); } };
  const applyProcess = async () => { if (!selected || !snapshot?.active_process) return; const priority = selected.patch.process.priority; const elevated = priority === "high" || priority === "realtime"; if (elevated) { setMessage(text("High and Realtime profile priority must be reviewed on CPU & Priority; it was not auto-applied.", "높음 및 실시간 우선도는 CPU 및 우선도 화면에서 검토해야 하며 자동 적용되지 않았습니다.")); return; } try { await commands.applyProcessSettings({ ...selected.patch.process, dangerous_priority_acknowledged: false }); setMessage(text("Profile process settings applied with readback.", "프로필 프로세스 설정을 적용하고 읽기 결과를 확인했습니다.")); } catch (error) { setMessage(commandErrorMessage(error, language)); } };
  const exportProfile = async (profile: CustomProfile) => { try { const saved = await commands.exportProfile(profile.id); setMessage(saved ? text(`Exported ${profile.name}.`, `${profile.name} 프로필을 내보냈습니다.`) : text("Export cancelled.", "내보내기를 취소했습니다.")); } catch (error) { setMessage(commandErrorMessage(error, language)); } };
  const cloneProfile = async () => { if (!selected) return; try { await commands.saveProfile({ ...selected, id: editId, name: editName, revision: 0 }); setMessage(text(`Saved ${editName}.`, `${editName} 프로필을 저장했습니다.`)); await refresh(); } catch (error) { setMessage(commandErrorMessage(error, language)); } };
  const renameProfile = async () => { if (!selected) return; try { const renamed = await commands.saveProfile({ ...selected, name: editName }); setSelected(renamed); setMessage(text(`Saved ${editName}.`, `${editName} 프로필 이름을 저장했습니다.`)); await refresh(); } catch (error) { setMessage(commandErrorMessage(error, language)); } };
  return <div className="page"><PageHeader title={text("Profiles", "프로필")} description={text("Save repeatable settings and exchange portable JSON profiles. Importing or selecting never auto-applies changes.", "반복 사용할 설정을 저장하고 JSON 프로필로 공유합니다. 가져오기나 선택만으로 설정이 자동 적용되지 않습니다.")} actions={<Button onClick={() => void importProfile()}><Upload aria-hidden="true" size={17} />{text("Import profile", "프로필 가져오기")}</Button>} />
    {message ? <Notice kind={message.startsWith("Saved") || message.startsWith("저장") || message.includes("applied") || message.includes("적용") || message.includes("내보냈") ? "success" : "warning"}>{message}</Notice> : null}
    <section className="section"><h2>{text("Save current settings", "현재 설정 저장")}</h2><p>{text("Creates a local profile snapshot. Review it before applying later.", "로컬 프로필 스냅샷을 만들며 나중에 적용하기 전에 다시 검토합니다.")}</p><div className="form-grid"><Field label={text("Profile id", "프로필 ID")}><input value={draftId} onChange={(e) => setDraftId(e.target.value)} /></Field><Field label={text("Display name", "표시 이름")}><input value={draftName} onChange={(e) => setDraftName(e.target.value)} /></Field><Button disabled={!draftId || !draftName} onClick={() => void saveCurrent()}><Save aria-hidden="true" size={17} />{text("Save current", "현재 설정 저장")}</Button></div></section>
    {candidate ? <section className="section"><h2>{text("Import preview", "가져오기 미리보기")}</h2><dl className="details"><div><dt>{text("Source", "출처")}</dt><dd>Wuwa ini Tool {candidate.preview.source_app_version}</dd></div><div><dt>{text("Exported", "내보낸 시간")}</dt><dd>{candidate.preview.exported_at}</dd></div><div><dt>{text("Managed options", "관리 옵션")}</dt><dd>{candidate.preview.patch.managed_ini.length}</dd></div><div><dt>{text("Custom options", "사용자 옵션")}</dt><dd>{candidate.preview.patch.custom_ini_entries.length}</dd></div></dl>{candidate.preview.warnings.map((warning) => <Notice kind="warning" key={warning}>{warningLabel(warning)}</Notice>)}<div className="form-grid"><Field label={text("Profile id", "프로필 ID")}><input value={id} onChange={(e) => setId(e.target.value)} /></Field><Field label={text("Display name", "표시 이름")}><input value={name} onChange={(e) => setName(e.target.value)} /></Field></div><Button disabled={!id || !name} variant="primary" onClick={() => void saveImport()}><Save aria-hidden="true" size={17} />{text("Save imported profile", "가져온 프로필 저장")}</Button></section> : null}
    <Notice>{text("Built-in presets are read-only. Preview them in Engine.ini and save a custom profile to clone their settings.", "기본 제공 프리셋은 읽기 전용입니다. Engine.ini에서 미리본 뒤 사용자 프로필로 저장하여 복제하세요.")}</Notice>
    <section className="section"><h2>{text("Saved profiles", "저장된 프로필")}</h2>{profiles.length ? <div className="list">{profiles.map((profile) => <article className="list-row" key={profile.id}><div><b>{profile.name}</b><span>{profile.id} · {text("revision", "리비전")} {profile.revision}</span></div><div className="list-row__meta"><span>{profile.patch.managed_ini.length + profile.patch.custom_ini_entries.length} {text("Engine.ini options", "Engine.ini 옵션")}</span><span>{priorityLabel(profile.patch.process.priority)}</span></div><div className="action-row"><Button onClick={() => void previewSelected(profile)}><Eye aria-hidden="true" size={17} />{text("Preview", "미리보기")}</Button><Button onClick={() => void exportProfile(profile)}><Download aria-hidden="true" size={17} />{text("Export", "내보내기")}</Button></div></article>)}</div> : <EmptyState title={text("No profiles yet", "프로필 없음")} description={text("Import a shared profile or save your current settings.", "공유 프로필을 가져오거나 현재 설정을 저장하세요.")} />}</section>
    {selected ? <section className="apply-panel"><h2>{selected.name} · {text("review", "검토")}</h2><Notice>{text("No part of this profile is applied until you use the separate confirmed actions below.", "아래의 개별 확인 작업을 실행하기 전에는 프로필의 어떤 설정도 적용되지 않습니다.")}</Notice><div className="form-grid"><Field label={text("Copy id", "복제 ID")}><input value={editId} onChange={(event) => setEditId(event.target.value)} /></Field><Field label={text("Profile name", "프로필 이름")}><input value={editName} onChange={(event) => setEditName(event.target.value)} /></Field><div className="action-row"><Button disabled={!editId || !editName} onClick={() => void cloneProfile()}>{text("Save copy", "복제 저장")}</Button><Button disabled={!editName} onClick={() => void renameProfile()}>{text("Rename", "이름 변경")}</Button></div></div>{iniPreview ? <><DiffView preview={iniPreview} /><label className="check-row"><input checked={confirmIni} onChange={(e) => setConfirmIni(e.target.checked)} type="checkbox" />{text("Confirm backup and apply this Engine.ini preview", "백업 후 이 Engine.ini 미리보기 적용을 확인합니다")}</label><Button disabled={!confirmIni} variant="primary" onClick={() => void applyIni()}>{text("Back up and apply Engine.ini", "백업 후 Engine.ini 적용")}</Button></> : <p>{text("No pending Engine.ini preview.", "대기 중인 Engine.ini 미리보기가 없습니다.")}</p>}<Button disabled={!snapshot?.active_process} onClick={() => void applyProcess()}>{text("Apply process settings separately", "프로세스 설정 별도 적용")}</Button>{!snapshot?.active_process ? <small>{text("Start the validated game before applying process settings.", "프로세스 설정을 적용하려면 검증된 게임을 실행하세요.")}</small> : null}</section> : null}
  </div>;
}
